### ISSUE TITLE
Poder subir PDF dentro de una subcarpeta

### ISSUE THREAD

**Issue by mihdicaballero** [LaTeXUy/pruebas-LaTeX-CI#1]
El objetivo es poder compilar un archivo .tex y usbir el PDF dentro una subcarpeta y no en el root directory directamente.

**Comment by jorgepz** [comment]
however... sugiero resolver primero esto https://github.com/LaTeXUy/pruebas-LaTeX-CI/issues/2 😄

**Comment by jorgepz** [comment]
las github actions https://github.com/actions/upload-artifact y https://github.com/actions/download-artifact tienen algunas opciones para apuntar a carpetas pero si no entiendo mal esto no hace referencia a subir o bajar del repo en sí, si no que del servidor en el cual se está haciendo la corrida del CI... no veo una forma clara de hacer una subida del pdf generado al repo en sí... pero tal vez me equivoque . cierro por ahora.
