### ISSUE TITLE
Lograr poner el PDF dentro del repositorio directo

### ISSUE THREAD

**Issue by mihdicaballero** [LaTeXUy/pruebas-LaTeX-CI#4]
Estuve viendo y se sube el zip, pero queda dentro del pull request. Mira:
![image](https://user-images.githubusercontent.com/29404688/158710629-33182831-8a8a-486c-a581-c29067d4f3d0.png)
Si le hacés clic ahi al "PDF" se te baja el zip con el PDF. Lo que falta es que lo ponga dentro del root de nuevo al PDF y no al zip.

**Comment by mihdicaballero** [comment]
Acá 
[https://github.com/actions/download-artifact](https://github.com/actions/download-artifact)
indica como se hace para descargar el artifact al respositorio.

Tenía como ejemplo que tenía que ser v3 el download artifact.

**Comment by mihdicaballero** [comment]
Todavía no lo logro enganchar, como que me pone 2 veces el path del root mismo, mirá:
![image](https://user-images.githubusercontent.com/29404688/158712281-f089587c-aa89-4b5a-8849-8b3e13c46566.png)
Tal vez se te ocurre como se resuelve @jorgepz

**Comment by jorgepz** [comment]
Retomé esto, parece que hay algunas cosas que actualmente no se pueden hacer para linkear el artifact... ni tener un enlace directo al último artifact generado https://stackoverflow.com/questions/63451187/is-it-possible-to-download-github-actions-artifacts-directly https://github.com/actions/upload-artifact/issues/27 ni tampoco que el artifact sea únicamente el pdf en lugar de un zip https://github.com/actions/upload-artifact/issues/107 https://github.com/actions/upload-artifact#zipped-artifact-downloads  y entiendo que tampoco bajar el archivo directamente al repo... cierro este issue por ahora. entiendo que uno tiene que cliquear en actions y cliquear en el artifact y descargar el pdf.
